export const MOCK_USERS = [
    // --- MENTORS ---
    {
        name: "Dr. Amara Okafor",
        email: "amara.okafor@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "Nigeria",
        career: "Senior AI Research Lead",
        company: "Google AI Accra",
        expertiseAreas: ["AI/ML", "Ethics in AI", "Research Projects"],
        skills: ["AI/ML", "Ethics in AI", "Research Projects"],
        yearsExperience: "10+ Years",
        experienceLevel: "Expert / Lead",
        bio: "Leading AI research focused on African languages and healthcare applications. I've mentored dozens of PhD students and early-career researchers across the continent.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop",
        sessionDuration: "1 Hour",
        preferredDays: ["Monday", "Wednesday", "Friday"],
        languages: ["English", "Igbo"],
        rating: 5.0
    },
    {
        name: "Kofi Ampah",
        email: "kofi.ampah@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "Ghana",
        career: "Cloud Solutions Architect",
        company: "AWS",
        expertiseAreas: ["SaaS", "DevTools", "Mobile Apps"],
        skills: ["SaaS", "DevTools", "Mobile Apps"],
        yearsExperience: "5-10 Years",
        experienceLevel: "Senior",
        bio: "Specialist in building highly scalable distributed systems. I help African startups navigate their journey from MVP to scale on the cloud.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
        sessionDuration: "45 Minutes",
        preferredDays: ["Tuesday", "Thursday"],
        languages: ["English", "Twi"],
        rating: 4.9
    },
    {
        name: "Zanele Mbeki",
        email: "zanele.mbeki@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "South Africa",
        career: "Product Design Director",
        company: "Paystack",
        expertiseAreas: ["Fintech", "Mobile Apps", "Products"],
        skills: ["Fintech", "Mobile Apps", "Products"],
        yearsExperience: "10+ Years",
        experienceLevel: "Expert / Lead",
        bio: "Passionate about creating inclusive financial products. I lead design teams that focus on user empathy and high-impact visual design.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
        sessionDuration: "1 Hour",
        preferredDays: ["Monday", "Tuesday", "Thursday"],
        languages: ["English", "Zulu"],
        rating: 4.8
    },
    {
        name: "Tarek Mansour",
        email: "tarek.mansour@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "Egypt",
        career: "Senior Fullstack Engineer",
        company: "Instabug",
        expertiseAreas: ["Web3/Crypto", "Mobile Apps", "DevTools"],
        skills: ["Web3/Crypto", "Mobile Apps", "DevTools"],
        yearsExperience: "5-10 Years",
        experienceLevel: "Senior",
        bio: "Building the next generation of web applications. I enjoy deep-diving into performance optimizations and complex state management.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
        sessionDuration: "30 Minutes",
        preferredDays: ["Sunday", "Monday", "Wednesday"],
        languages: ["Arabic", "English"],
        rating: 4.7
    },
    {
        name: "Idriis Farah",
        email: "idriis.farah@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "Kenya",
        career: "AgTech CTO",
        company: "Hello Tractor",
        expertiseAreas: ["AgTech", "AI/ML", "SaaS"],
        skills: ["AgTech", "AI/ML", "SaaS"],
        yearsExperience: "10+ Years",
        experienceLevel: "Expert / Lead",
        bio: "Leveraging technology to solve food security in Africa. I can help with tech strategy, team building, and fractional CTO advice.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
        sessionDuration: "1 Hour",
        preferredDays: ["Friday", "Saturday"],
        languages: ["English", "Swahili"],
        rating: 5.0
    },
    {
        name: "Maya Patel",
        email: "maya.patel@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentor",
        country: "South Africa",
        career: "Healthcare Tech Lead",
        company: "Discovery Life",
        expertiseAreas: ["Healthcare/Tech", "AI/ML", "EdTech"],
        skills: ["Healthcare/Tech", "AI/ML", "EdTech"],
        yearsExperience: "5-10 Years",
        experienceLevel: "Senior",
        bio: "Bridging clinical knowledge with software engineering. I mentor women in tech looking to lead high-stakes engineering projects.",
        onboarded: true,
        profileImage: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=400&h=400&fit=crop",
        sessionDuration: "45 Minutes",
        preferredDays: ["Wednesday", "Thursday"],
        languages: ["English", "Hindi"],
        rating: 4.9
    },

    // --- MENTEES ---
    {
        name: "Chidi Azeez",
        email: "chidi.azeez@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentee",
        country: "Nigeria",
        career: "Entry-level Dev",
        company: "Intern at Andela",
        interests: ["AI/ML", "SaaS", "Mobile Apps"],
        skills: ["AI/ML", "SaaS", "Mobile Apps"],
        yearsExperience: "1-2 Years",
        experienceLevel: "Entry",
        bio: "I'm a self-taught developer looking to transition into AI. I want to build tools that help African students learn better.",
        onboarded: true,
        profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chidi"
    },
    {
        name: "Sarah Kamau",
        email: "sarah.kamau@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentee",
        country: "Kenya",
        career: "Junior UI/UX Designer",
        company: "Little App",
        interests: ["Mobile Apps", "Products", "Healthcare/Tech"],
        skills: ["Mobile Apps", "Products", "Healthcare/Tech"],
        yearsExperience: "1-2 Years",
        experienceLevel: "Entry",
        bio: "Aspiring Product Director. I want to learn more about design systems and how to lead cross-functional product teams.",
        onboarded: true,
        profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah"
    },
    {
        name: "Jean-Claude Bide",
        email: "jean.bide@mentor.match",
        password: "MentorMatch2026!Auth",
        role: "mentee",
        country: "Rwanda",
        career: "Backend Intern",
        company: "Kira Labs",
        interests: ["SaaS", "DevTools", "Fintech"],
        skills: ["SaaS", "DevTools", "Fintech"],
        yearsExperience: "1-2 Years",
        experienceLevel: "Entry",
        bio: "Graduate from African Leadership University. I'm focusing on backend architecture and API performance in the fintech space.",
        onboarded: true,
        profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean"
    },
    {
        name: "Lina Mahrez",
        email: "lina.mahrez@mentor.match",
        password: "Password123!",
        role: "mentee",
        country: "Tunisia",
        career: "Data Analyst",
        company: "Exo Group",
        interests: ["AI/ML", "EdTech", "AgTech"],
        skills: ["AI/ML", "EdTech", "AgTech"],
        yearsExperience: "3-5 Years",
        experienceLevel: "Mid-level",
        bio: "Data enthusiast looking to specialize in ML engineering for social impact projects in North Africa.",
        onboarded: true,
        profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lina"
    }
];
